Fix failed build
The build failed with the following error:
ERROR in src/app/main/main.component.html(5,3): Property 'containssets' does not exist on type 'MainComponent'.